#
# Circle CI configuration. Runs each time we push a new commit to Github.
#
# This file is derived from the project's Dockerfile, which we use for
# local testing.
#
version: 2.1
jobs:
  build:
    docker:
      - image: returntocorp/ocaml:ubuntu

    # 'tree-sitter generate' needs a lot of memory. CircleCI offers
    # the following types of hosts:
    # - medium+: 6 GB
    # - large: 8 GB
    # - xlarge: 16 GB
    #resource_class: xlarge

    working_directory: ~/ocaml-tree-sitter
    steps:
      - checkout
      - run:
          name: fetch submodules
          command: git submodule update --init --recursive --depth 1
      - run:
          name: set up node
          command: ./core/scripts/setup-node
      - run:
          name: install dependencies
          command: opam exec -- make setup
      - run:
          name: build
          command: opam exec -- make
      - run:
          name: install
          command: opam exec -- make install
      - run:
          name: core tests
          command: opam exec -- make -C core test
      - run:
          name: test languages
          no_output_timeout: 60m
          command: opam exec -- make lang
  stat:
    docker:
      - image: returntocorp/ocaml:ubuntu

    # See earlier note about memory requirements.
    #resource_class: xlarge

    working_directory: ~/ocaml-tree-sitter
    steps:
      - checkout
      - run:
          name: fetch submodules
          command: git submodule update --init --recursive --depth 1
      - run:
          name: set up node
          command: ./core/scripts/setup-node
      - run:
          name: install tree-sitter lib
          command: ./core/scripts/install-tree-sitter-lib
      - run:
          name: install tree-sitter executable
          command: ./core/scripts/install-tree-sitter-cli
      - run:
          name: install dependencies
          command: opam exec -- make setup
      - run:
          name: build
          command: opam exec -- make
      - run:
          name: install
          command: opam exec -- make install
      - run:
          name: run parsing stats
          no_output_timeout: 60m
          command: opam exec -- make stat
      - run:
          name: upload parsing stats
          command: python3 ./scripts/upload-stat lang/stat.txt
      - store_artifacts:
          path: lang/stat.txt

workflows:
  version: 2

  build-on-commit:
    # Default trigger, on commit.
    jobs:
      - build

  scheduled-stats:
    triggers:
      - schedule:
          # Run at 00:00 every day, UTC.
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - stat:
          # Run only on these branches (each pushing different images)
          filters:
            branches:
              only:
                - main

  # This is for testing or for forcing a stats job. Requires pushing
  # to a branch named 'stats'.
  stats-on-commit:
    jobs:
      - stat:
          filters:
            branches:
              only:
                - stats
